# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.clientinfo:
          class: AppBundle\Services\ClientInfo
          arguments: ['@templating' , "@service_container" ]

      app.menu.builder:
          class: AppBundle\Menu\MenuBuilder
          arguments: [ "@knp_menu.factory" , "@doctrine.orm.entity_manager" , "@service_container" ]
          tags:
              - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
              - { name: knp_menu.menu_builder, method: createLangMenu, alias: lang }
          voters:
              content_identity:
                  enabled: true
                  content_key: myKey


      app.twig_extension:
          class: AppBundle\Twig\AppExtension
          public: false
          tags:
              - { name: twig.extension }